import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    padding: 24,
    gap: 12,
  },
  header: {
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  kicker: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#be123c',
    fontWeight: '700',
  },
  title: {
    marginTop: 8,
    fontSize: 28,
    fontWeight: '700',
    color: '#0f172a',
  },
  mutedText: {
    color: '#64748b',
    fontSize: 13,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: '600',
  },
  noticeText: {
    color: '#be123c',
    fontSize: 13,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  bottomNav: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 6,
    justifyContent: 'center',
  },
  bottomNavButton: {
    minWidth: 76,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  bottomNavLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bottomNavButtonActive: {
    backgroundColor: '#be123c',
    borderColor: '#be123c',
  },
  bottomNavText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  bottomNavTextActive: {
    color: '#ffffff',
  },
  badge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#f59e0b',
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: '#111827',
    fontSize: 10,
    fontWeight: '700',
  },
  tabRow: {
    paddingHorizontal: 12,
    paddingBottom: 8,
    gap: 8,
  },
  tabButton: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#ffffff',
  },
  tabButtonActive: {
    backgroundColor: '#be123c',
    borderColor: '#be123c',
  },
  tabText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '600',
  },
  tabTextActive: {
    color: '#ffffff',
  },
  sectionList: {
    paddingHorizontal: 12,
    paddingBottom: 24,
    gap: 10,
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  listItem: {
    borderColor: '#f1f5f9',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    gap: 4,
  },
  listItemActive: {
    borderColor: '#be123c',
    backgroundColor: '#fff1f2',
  },
  listTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
  },
  listMeta: {
    fontSize: 12,
    color: '#64748b',
  },
  metricText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '600',
  },
  profilePhoto: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignSelf: 'flex-start',
  },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  inputError: {
    borderColor: '#b91c1c',
  },
  primaryButton: {
    backgroundColor: '#be123c',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  primaryButtonLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  subtleButton: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#ffffff',
  },
  subtleButtonLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  rowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  rowInput: {
    flex: 1,
  },
  rowButton: {
    minWidth: 96,
  },
  pill: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillActive: {
    borderColor: '#be123c',
    backgroundColor: '#ffe4e6',
  },
  pillText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
});
